### ISSUE TITLE
Can you provide a more accuracy model for dataset?

### ISSUE THREAD

**Issue by densechen** [NVlabs/latentfusion#1]
Hi, 
    Thanks for providing so nice code and dataset. I have download the dataset but I found that, the provided models for instance are so noise that hard to be used. Can you provide a better model obj for that?
Best

**Comment by arsalan-mousavian** [comment]
The provided 3D models are constructed using KinectFusion and similar SLAM methods from sparse views of objects. These models would be of lower quality compared to the obj models you would get with 3D scanner or specialized camera rigs that are used in other datasets. However, if you want a robot to add a new object, the robot does not have access to that special hardware for scanning objects and it has to build the model from multiple views. Our method bypasses these challenges by using just the registered poses from each reference view and use the actual RGB-D image instead of mesh. We released the code and data to encourage vision community to facilitate making progress on the problem of zero-shot pose estimation where constructing high quality meshes is not possible.

**Comment by densechen** [comment]
@arsalan-mousavian Thanks for your reply. However I think if accuracy models could be provided, we can use this dataset for more different tasks, but not limited to this one.

**Comment by keunhong** [comment]
Hi Chen,

Unfortunately the quality of the meshes is a limitation of the type of data capture. We free-hand captured these objects using a commodity depth camera so the registration isn't perfect. In fact, we did this on purpose to demonstrate that our method works on noisy data like this :)

You could probably get better meshes by registering the input images your self with a tuned implementation of something like KinectFusion, but that's not the focus of our work.
